# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic (*sub-namespace, see below)
# - topic   : input topic of sensor_msgs::Joy type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

#TODO : donner des noms radoms
#TODO : topics a specifer au moment de test
joy_mux:
  ros__parameters:
    topics:
      joy1:
        topic   : joy1
        timeout : 0.5
        priority: 10
      joy2:
        topic   : joy2
        timeout : 0.5
        priority: 100
      joy3:
        topic   : joy3
        timeout : 0.5
        priority: 90
      joy4:
        topic   : joy4
        timeout : 0.5
        priority: 100
